// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import UIKit;
@import CoreGraphics;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSNumber;
@class NSDictionary;

SWIFT_CLASS("_TtC14MercadoPagoSDK7Address")
@interface Address : NSObject
@property (nonatomic, copy) NSString * _Nullable streetName;
@property (nonatomic, strong) NSNumber * _Nullable streetNumber;
@property (nonatomic, copy) NSString * _Nullable zipCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithStreetName:(NSString * _Nullable)streetName streetNumber:(NSNumber * _Nullable)streetNumber zipCode:(NSString * _Nullable)zipCode OBJC_DESIGNATED_INITIALIZER;
+ (Address * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
@end

@class Cause;

SWIFT_CLASS("_TtC14MercadoPagoSDK12ApiException")
@interface ApiException : NSObject
@property (nonatomic, strong) Cause * _Null_unspecified cause;
@property (nonatomic, copy) NSString * _Null_unspecified error;
@property (nonatomic, copy) NSString * _Null_unspecified message;
@property (nonatomic) NSInteger status;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSData;

SWIFT_CLASS("_TtC14MercadoPagoSDK12Serializable")
@interface Serializable : NSObject

/// Converts the class to a dictionary.
///
/// \returns  The class as an NSDictionary.
- (NSDictionary * _Nonnull)toDictionary;

/// Converts the class to JSON.
///
/// \returns  The class as JSON, wrapped in NSData.
- (NSData * _Nullable)toJson:(BOOL)prettyPrinted;

/// Converts the class to a JSON string.
///
/// \returns  The class as a JSON string.
- (NSString * _Nullable)toJsonString:(BOOL)prettyPrinted;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK3Bin")
@interface Bin : Serializable
@property (nonatomic, copy) NSString * _Null_unspecified exclusionPattern;
@property (nonatomic, copy) NSString * _Null_unspecified installmentsPattern;
@property (nonatomic, copy) NSString * _Null_unspecified pattern;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Bin * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
@end

@class Cardholder;
@class NSDate;
@class PaymentMethod;
@class Issuer;
@class SecurityCode;

SWIFT_CLASS("_TtC14MercadoPagoSDK4Card")
@interface Card : NSObject
@property (nonatomic, strong) Cardholder * _Nullable cardHolder;
@property (nonatomic, copy) NSString * _Nullable customerId;
@property (nonatomic, strong) NSDate * _Nullable dateCreated;
@property (nonatomic, strong) NSDate * _Nullable dateLastUpdated;
@property (nonatomic) NSInteger expirationMonth;
@property (nonatomic) NSInteger expirationYear;
@property (nonatomic, copy) NSString * _Nullable firstSixDigits;
@property (nonatomic, strong) NSNumber * _Nonnull _id;
@property (nonatomic, copy) NSString * _Nullable lastFourDigits;
@property (nonatomic, strong) PaymentMethod * _Nullable paymentMethod;
@property (nonatomic, strong) Issuer * _Nullable issuer;
@property (nonatomic, strong) SecurityCode * _Nullable securityCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Card * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (BOOL)isSecurityCodeRequired;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK10CardIssuer")
@interface CardIssuer : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified _id;
@property (nonatomic, copy) NSString * _Null_unspecified name;
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified labels;
- (nonnull instancetype)initWith_id:(NSString * _Nonnull)_id name:(NSString * _Nullable)name labels:(NSArray<NSString *> * _Nonnull)labels OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK10CardNumber")
@interface CardNumber : Serializable
@property (nonatomic) NSInteger length;
@property (nonatomic, copy) NSString * _Null_unspecified validation;
+ (CardNumber * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class Device;
@class NSError;
@class IdentificationType;

SWIFT_CLASS("_TtC14MercadoPagoSDK9CardToken")
@interface CardToken : NSObject
@property (nonatomic, copy) NSString * _Nullable cardNumber;
@property (nonatomic, copy) NSString * _Nullable securityCode;
@property (nonatomic) NSInteger expirationMonth;
@property (nonatomic) NSInteger expirationYear;
@property (nonatomic, strong) Cardholder * _Nullable cardholder;
@property (nonatomic, strong) Device * _Nullable device;
- (nonnull instancetype)initWithCardNumber:(NSString * _Nullable)cardNumber expirationMonth:(NSInteger)expirationMonth expirationYear:(NSInteger)expirationYear securityCode:(NSString * _Nullable)securityCode cardholderName:(NSString * _Nonnull)cardholderName docType:(NSString * _Nonnull)docType docNumber:(NSString * _Nonnull)docNumber OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)normalizeCardNumber:(NSString * _Nullable)number;
- (BOOL)validate;
- (BOOL)validate:(BOOL)includeSecurityCode;
- (NSError * _Nullable)validateCardNumber;
- (NSError * _Nullable)validateCardNumber:(PaymentMethod * _Nonnull)paymentMethod;
- (NSError * _Nullable)validateSecurityCode;
- (NSError * _Nullable)validateSecurityCode:(NSString * _Nullable)securityCode;
- (NSError * _Nullable)validateSecurityCodeWithPaymentMethod:(PaymentMethod * _Nonnull)paymentMethod;
- (NSError * _Nullable)validateSecurityCodeWithPaymentMethod:(NSString * _Nonnull)securityCode paymentMethod:(PaymentMethod * _Nonnull)paymentMethod bin:(NSString * _Nonnull)bin;
- (NSError * _Nullable)validateExpiryDate;
- (NSError * _Nullable)validateExpiryDate:(NSInteger)month year:(NSInteger)year;
- (BOOL)validateExpMonth:(NSInteger)month;
- (BOOL)validateExpYear:(NSInteger)year;
- (NSError * _Nullable)validateIdentification;
- (NSError * _Nullable)validateIdentificationType;
- (NSError * _Nullable)validateIdentificationNumber;
- (NSError * _Nullable)validateIdentificationNumber:(IdentificationType * _Nullable)identificationType;
- (NSError * _Nullable)validateCardholderName;
- (BOOL)hasYearPassed:(NSInteger)year;
- (BOOL)hasMonthPassed:(NSInteger)year month:(NSInteger)month;
- (NSInteger)normalizeYear:(NSInteger)year;
- (BOOL)checkLuhn:(NSString * _Nonnull)cardNumber;
- (NSString * _Nullable)getBin;
- (NSString * _Nonnull)toJSONString;
@end

@class Identification;

SWIFT_CLASS("_TtC14MercadoPagoSDK10Cardholder")
@interface Cardholder : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, strong) Identification * _Nullable identification;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Cardholder * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Cause")
@interface Cause : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified code;
@property (nonatomic, copy) NSString * _Null_unspecified _description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSCoder;

SWIFT_CLASS("_TtC14MercadoPagoSDK34CongratsPaymentMethodTableViewCell")
@interface CongratsPaymentMethodTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end

@class UITableView;
@class NSIndexPath;
@class Payment;

SWIFT_CLASS("_TtC14MercadoPagoSDK22CongratsViewController")
@interface CongratsViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITextFieldDelegate, UITableViewDataSource>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)declareAndInitCells;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (void)_setTitle:(Payment * _Nonnull)payment;
- (void)_setIcon:(Payment * _Nonnull)payment;
- (void)setDescription:(Payment * _Nonnull)payment;
- (void)setAmount:(Payment * _Nonnull)payment;
- (void)setPaymentId:(Payment * _Nonnull)payment;
- (void)setPaymentMethodDescription:(Payment * _Nonnull)payment;
- (void)setDateCreated:(Payment * _Nonnull)payment;
- (void)setButtonText:(Payment * _Nonnull)payment;
- (void)submitForm;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK8Currency")
@interface Currency : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified _id;
@property (nonatomic, copy) NSString * _Null_unspecified _description;
@property (nonatomic, copy) NSString * _Null_unspecified symbol;
@property (nonatomic) NSInteger decimalPlaces;
@end

@class Phone;

SWIFT_CLASS("_TtC14MercadoPagoSDK8Customer")
@interface Customer : NSObject
@property (nonatomic, strong) Address * _Nullable address;
@property (nonatomic, copy) NSArray<Card *> * _Nullable cards;
@property (nonatomic, strong) NSNumber * _Nullable defaultCard;
@property (nonatomic, copy) NSString * _Nullable _description;
@property (nonatomic, strong) NSDate * _Nullable dateCreated;
@property (nonatomic, strong) NSDate * _Nullable dateLastUpdated;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable _id;
@property (nonatomic, strong) Identification * _Nullable identification;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, strong) NSDictionary * _Nullable metadata;
@property (nonatomic, strong) Phone * _Nullable phone;
@property (nonatomic, strong) NSDate * _Nullable registrationDate;
+ (Customer * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27CustomerCardsViewController")
@interface CustomerCardsViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nonnull instancetype)initWithCards:(NSArray<Card *> * _Nullable)cards callback:(void (^ _Nonnull)(Card * _Nullable))callback OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)loadCards;
- (void)newCard;
@end

@class Fingerprint;

SWIFT_CLASS("_TtC14MercadoPagoSDK6Device")
@interface Device : NSObject
@property (nonatomic, strong) Fingerprint * _Null_unspecified fingerprint;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK8Discount")
@interface Discount : NSObject
@property (nonatomic, strong) NSNumber * _Nonnull amountOff;
@property (nonatomic, strong) NSNumber * _Nonnull couponAmount;
@property (nonatomic, copy) NSString * _Null_unspecified currencyId;
@property (nonatomic) NSInteger _id;
@property (nonatomic, copy) NSString * _Null_unspecified name;
@property (nonatomic, strong) NSNumber * _Nonnull percentOff;
+ (Discount * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18ErrorTableViewCell")
@interface ErrorTableViewCell : UITableViewCell
@property (nonatomic) CGFloat height;
- (void)setError:(NSString * _Nullable)error;
- (void)focus;
- (BOOL)hasError;
- (CGFloat)getHeight;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK10FeesDetail")
@interface FeesDetail : NSObject
@property (nonatomic) double amount;
@property (nonatomic) double amountRefunded;
@property (nonatomic, copy) NSString * _Null_unspecified feePayer;
@property (nonatomic, copy) NSString * _Null_unspecified type;
+ (FeesDetail * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK11Fingerprint")
@interface Fingerprint : NSObject
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable fingerprint;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)toJSONString;
- (NSDictionary<NSString *, id> * _Nonnull)deviceFingerprint;
- (NSArray * _Nullable)devicesID;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18MercadoPagoService")
@interface MercadoPagoService : NSObject
- (void)request:(NSString * _Nonnull)uri params:(NSString * _Nullable)params body:(id _Nullable)body method:(NSString * _Nonnull)method success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end

@class SavedCardToken;

SWIFT_CLASS("_TtC14MercadoPagoSDK14GatewayService")
@interface GatewayService : MercadoPagoService
- (void)getToken:(NSString * _Nonnull)url method:(NSString * _Nonnull)method public_key:(NSString * _Nonnull)public_key savedCardToken:(SavedCardToken * _Nonnull)savedCardToken success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)getToken:(NSString * _Nonnull)url method:(NSString * _Nonnull)method public_key:(NSString * _Nonnull)public_key cardToken:(CardToken * _Nonnull)cardToken success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK16GenericErrorView")
@interface GenericErrorView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setErrorMessage:(NSString * _Nonnull)errorMessage;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14Identification")
@interface Identification : NSObject
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable number;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(NSString * _Nullable)type number:(NSString * _Nullable)number OBJC_DESIGNATED_INITIALIZER;
+ (Identification * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK21IdentificationService")
@interface IdentificationService : MercadoPagoService
- (void)getIdentificationTypes:(NSString * _Nonnull)method uri:(NSString * _Nonnull)uri public_key:(NSString * _Nullable)public_key privateKey:(NSString * _Nullable)privateKey success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18IdentificationType")
@interface IdentificationType : NSObject
@property (nonatomic, copy) NSString * _Nullable _id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic) NSInteger minLength;
@property (nonatomic) NSInteger maxLength;
+ (IdentificationType * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayerCost;

SWIFT_CLASS("_TtC14MercadoPagoSDK11Installment")
@interface Installment : NSObject
@property (nonatomic, strong) Issuer * _Null_unspecified issuer;
@property (nonatomic, copy) NSArray<PayerCost *> * _Null_unspecified payerCosts;
@property (nonatomic, copy) NSString * _Null_unspecified paymentMethodId;
@property (nonatomic, copy) NSString * _Null_unspecified paymentTypeId;
+ (Installment * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK24InstallmentTableViewCell")
@interface InstallmentTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithPayerCost:(PayerCost * _Nonnull)payerCost amount:(double)amount;
@end

@class NSBundle;

SWIFT_CLASS("_TtC14MercadoPagoSDK26InstallmentsViewController")
@interface InstallmentsViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK6Issuer")
@interface Issuer : NSObject
@property (nonatomic, strong) NSNumber * _Nullable _id;
@property (nonatomic, copy) NSString * _Nullable name;
+ (Issuer * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK19IssuerTableViewCell")
@interface IssuerTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithIssuer:(Issuer * _Nonnull)issuer;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK21IssuersViewController")
@interface IssuersViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK4Item")
@interface Item : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified _id;
@property (nonatomic) NSInteger quantity;
@property (nonatomic) double unitPrice;
- (nonnull instancetype)initWith_id:(NSString * _Nonnull)_id quantity:(NSInteger)quantity unitPrice:(double)unitPrice OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)toJSONString;
@end

@class Setting;
@class UITextField;

SWIFT_CLASS("_TtC14MercadoPagoSDK25MPCardNumberTableViewCell")
@interface MPCardNumberTableViewCell : ErrorTableViewCell <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified cardNumberTextField;
@property (nonatomic, strong) Setting * _Null_unspecified setting;
- (void)focus;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Null_unspecified)getCardNumber;
- (void)setIcon:(NSString * _Nullable)pmId;
- (void)_setSetting:(Setting * _Null_unspecified)setting;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate> _Nonnull)delegate;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK29MPCardholderNameTableViewCell")
@interface MPCardholderNameTableViewCell : ErrorTableViewCell
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified cardholderNameTextField;
- (void)focus;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Null_unspecified)getCardholderName;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate> _Nonnull)delegate;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK29MPExpirationDateTableViewCell")
@interface MPExpirationDateTableViewCell : ErrorTableViewCell <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified expirationDateTextField;
- (void)focus;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSInteger)getExpirationMonth;
- (NSInteger)getExpirationYear;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate> _Nonnull)delegate;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27MPInstallmentsTableViewCell")
@interface MPInstallmentsTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithPayerCost:(PayerCost * _Nullable)payerCost amount:(double)amount;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK33MPPaymentMethodEmptyTableViewCell")
@interface MPPaymentMethodEmptyTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK28MPPaymentMethodTableViewCell")
@interface MPPaymentMethodTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithCard:(Card * _Nullable)card;
- (void)fillWithCardTokenAndPaymentMethod:(CardToken * _Nullable)card paymentMethod:(PaymentMethod * _Nullable)paymentMethod;
- (void)fillWithPaymentMethod:(PaymentMethod * _Nullable)paymentMethod;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27MPSecurityCodeTableViewCell")
@interface MPSecurityCodeTableViewCell : ErrorTableViewCell
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified securityCodeTextField;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Null_unspecified)getSecurityCode;
- (void)fillWithPaymentMethod:(PaymentMethod * _Nonnull)pm;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK9MPToolbar")
@interface MPToolbar : UIToolbar
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPickerView;

SWIFT_CLASS("_TtC14MercadoPagoSDK21MPUserIdTableViewCell")
@interface MPUserIdTableViewCell : ErrorTableViewCell <UITextFieldDelegate, UIPickerViewDelegate, UIPickerViewDataSource>
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified userIdTypeTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified userIdValueTextField;
@property (nonatomic, strong) IBOutlet UIPickerView * _Null_unspecified pickerIdentificationType;
@property (nonatomic, copy) NSArray<IdentificationType *> * _Nonnull identificationTypes;
@property (nonatomic, strong) IdentificationType * _Nullable identificationType;
- (void)focus;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component;
- (NSString * _Nullable)pickerView:(UIPickerView * _Nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component;
- (void)pickerView:(UIPickerView * _Nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
- (BOOL)textFieldShouldBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string;
- (void)setFormWithIndex:(NSInteger)row;
- (void)awakeFromNib;
- (void)_setIdentificationTypes:(NSArray<IdentificationType *> * _Nullable)identificationTypes;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Null_unspecified)getUserIdType;
- (NSString * _Null_unspecified)getUserIdValue;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate> _Nonnull)delegate;
@end

@class NewCardViewController;
@class PaymentMethodsViewController;
@class PromoViewController;
@class VaultViewController;
@class Token;
@class UIImage;
@class UINavigationController;
@class UIAlertView;

SWIFT_CLASS("_TtC14MercadoPagoSDK11MercadoPago")
@interface MercadoPago : NSObject <UIAlertViewDelegate>
+ (NSString * _Nonnull)PUBLIC_KEY;
+ (NSString * _Nonnull)PRIVATE_KEY;
+ (NSInteger)ERROR_KEY_CODE;
+ (NSInteger)ERROR_API_CODE;
+ (NSInteger)ERROR_UNKNOWN_CODE;
+ (NSInteger)ERROR_NOT_INSTALLMENTS_FOUND;
+ (NSInteger)ERROR_PAYMENT;
@property (nonatomic, copy) NSString * _Nullable privateKey;
@property (nonatomic, copy) NSString * _Nullable publicKey;
@property (nonatomic, copy) NSString * _Nullable paymentMethodId;
@property (nonatomic, copy) NSString * _Nullable paymentTypeId;
- (nonnull instancetype)initWithPublicKey:(NSString * _Nonnull)publicKey OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithKeyType:(NSString * _Nullable)keyType key:(NSString * _Nullable)key OBJC_DESIGNATED_INITIALIZER;
+ (CustomerCardsViewController * _Nonnull)startCustomerCardsViewController:(NSArray<Card *> * _Nonnull)cards callback:(void (^ _Nonnull)(Card * _Nullable))callback;
+ (NewCardViewController * _Nonnull)startNewCardViewController:(NSString * _Nonnull)keyType key:(NSString * _Nonnull)key paymentMethod:(PaymentMethod * _Nonnull)paymentMethod requireSecurityCode:(BOOL)requireSecurityCode callback:(void (^ _Nonnull)(CardToken * _Nonnull))callback;
+ (PaymentMethodsViewController * _Nonnull)startPaymentMethodsViewController:(NSString * _Nonnull)merchantPublicKey supportedPaymentTypes:(NSArray<NSString *> * _Nonnull)supportedPaymentTypes callback:(void (^ _Nonnull)(PaymentMethod * _Nonnull))callback;
+ (IssuersViewController * _Nonnull)startIssuersViewController:(NSString * _Nonnull)merchantPublicKey paymentMethod:(PaymentMethod * _Nonnull)paymentMethod callback:(void (^ _Nonnull)(Issuer * _Nonnull))callback;
+ (InstallmentsViewController * _Nonnull)startInstallmentsViewController:(NSArray<PayerCost *> * _Nonnull)payerCosts amount:(double)amount callback:(void (^ _Nonnull)(PayerCost * _Nullable))callback;
+ (CongratsViewController * _Nonnull)startCongratsViewController:(Payment * _Nonnull)payment paymentMethod:(PaymentMethod * _Nonnull)paymentMethod;
+ (PromoViewController * _Nonnull)startPromosViewController:(NSString * _Nonnull)merchantPublicKey;
+ (VaultViewController * _Nonnull)startVaultViewController:(NSString * _Nonnull)merchantPublicKey merchantBaseUrl:(NSString * _Nullable)merchantBaseUrl merchantGetCustomerUri:(NSString * _Nullable)merchantGetCustomerUri merchantAccessToken:(NSString * _Nullable)merchantAccessToken amount:(double)amount supportedPaymentTypes:(NSArray<NSString *> * _Nonnull)supportedPaymentTypes callback:(void (^ _Nonnull)(PaymentMethod * _Nonnull, NSString * _Nullable, NSNumber * _Nullable, NSInteger))callback;
- (void)createNewCardToken:(CardToken * _Nonnull)cardToken success:(void (^ _Nonnull)(Token * _Nullable))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)createToken:(SavedCardToken * _Nonnull)savedCardToken success:(void (^ _Nonnull)(Token * _Nullable))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)getPaymentMethods:(void (^ _Nonnull)(NSArray<PaymentMethod *> * _Nullable))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)getIdentificationTypes:(void (^ _Nonnull)(NSArray<IdentificationType *> * _Nullable))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)getInstallments:(NSString * _Nonnull)bin amount:(double)amount issuerId:(NSNumber * _Nullable)issuerId paymentTypeId:(NSString * _Nonnull)paymentTypeId success:(void (^ _Nonnull)(NSArray<Installment *> * _Nullable))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)getIssuers:(NSString * _Nonnull)paymentMethodId success:(void (^ _Nonnull)(NSArray<Issuer *> * _Nullable))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
+ (BOOL)isCardPaymentType:(NSString * _Nonnull)paymentTypeId;
+ (NSBundle * _Nullable)getBundle;
+ (UIImage * _Nullable)getImage:(NSString * _Nonnull)name;
+ (CGRect)screenBoundsFixedToPortraitOrientation;
+ (void)showAlertViewWithError:(NSError * _Nullable)error nav:(UINavigationController * _Nullable)nav;
- (void)alertView:(UIAlertView * _Nonnull)alertView clickedButtonAtIndex:(NSInteger)buttonIndex;
@end



SWIFT_CLASS("_TtC14MercadoPagoSDK15MerchantPayment")
@interface MerchantPayment : NSObject
@property (nonatomic, strong) NSNumber * _Nonnull cardIssuerId;
@property (nonatomic, copy) NSString * _Null_unspecified cardToken;
@property (nonatomic) NSInteger campaignId;
@property (nonatomic) NSInteger installments;
@property (nonatomic, strong) Item * _Null_unspecified item;
@property (nonatomic, copy) NSString * _Null_unspecified merchantAccessToken;
@property (nonatomic, copy) NSString * _Null_unspecified paymentMethodId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithItem:(Item * _Nonnull)item installments:(NSInteger)installments cardIssuerId:(NSNumber * _Nonnull)cardIssuerId token:(NSString * _Nonnull)token paymentMethodId:(NSString * _Nonnull)paymentMethodId campaignId:(NSInteger)campaignId merchantAccessToken:(NSString * _Nonnull)merchantAccessToken OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14MerchantServer")
@interface MerchantServer : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (void)getCustomer:(NSString * _Nonnull)merchantBaseUrl merchantGetCustomerUri:(NSString * _Nonnull)merchantGetCustomerUri merchantAccessToken:(NSString * _Nonnull)merchantAccessToken success:(void (^ _Nonnull)(Customer * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
+ (void)createPayment:(NSString * _Nonnull)merchantBaseUrl merchantPaymentUri:(NSString * _Nonnull)merchantPaymentUri payment:(MerchantPayment * _Nonnull)payment success:(void (^ _Nonnull)(Payment * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end

@class NSMutableData;

SWIFT_CLASS("_TtC14MercadoPagoSDK15MerchantService")
@interface MerchantService : MercadoPagoService
@property (nonatomic, strong) NSMutableData * _Nonnull data;
- (void)getCustomer:(NSString * _Nonnull)method merchant_access_token:(NSString * _Nonnull)merchant_access_token success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)createPayment:(NSString * _Nonnull)method payment:(MerchantPayment * _Nonnull)payment success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end


@interface NSDictionary (SWIFT_EXTENSION(MercadoPagoSDK))
- (BOOL)isKeyValid:(NSString * _Nonnull)dictKey;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK21NewCardViewController")
@interface NewCardViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (NSInteger)getIndexForObject:(id _Nonnull)object;
- (void)scrollToRow:(NSIndexPath * _Nonnull)indexPath;
- (void)focusAndScrollForIndex:(NSInteger)index;
- (void)prev:(id _Nullable)object;
- (void)next:(id _Nullable)object;
- (void)done:(id _Nullable)object;
- (void)prepareTableView;
- (void)submitForm;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)viewDidLayoutSubviews;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayCell:(UITableViewCell * _Nonnull)cell forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)validateForm:(CardToken * _Nonnull)cardToken;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Order")
@interface Order : NSObject
@property (nonatomic) NSInteger _id;
@property (nonatomic, copy) NSString * _Null_unspecified type;
+ (Order * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK9PayerCost")
@interface PayerCost : NSObject
@property (nonatomic) NSInteger installments;
@property (nonatomic) double installmentRate;
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified labels;
@property (nonatomic) double minAllowedAmount;
@property (nonatomic) double maxAllowedAmount;
@property (nonatomic, copy) NSString * _Null_unspecified recommendedMessage;
@property (nonatomic) double installmentAmount;
@property (nonatomic) double totalAmount;
- (nonnull instancetype)initWithInstallments:(NSInteger)installments installmentRate:(double)installmentRate labels:(NSArray<NSString *> * _Nonnull)labels minAllowedAmount:(double)minAllowedAmount maxAllowedAmount:(double)maxAllowedAmount recommendedMessage:(NSString * _Null_unspecified)recommendedMessage installmentAmount:(double)installmentAmount totalAmount:(double)totalAmount OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (PayerCost * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
@end

@class Refund;
@class TransactionDetails;

SWIFT_CLASS("_TtC14MercadoPagoSDK7Payment")
@interface Payment : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified callForAuthorizeId;
@property (nonatomic, strong) Card * _Null_unspecified card;
@property (nonatomic, copy) NSString * _Null_unspecified currencyId;
@property (nonatomic, strong) NSDate * _Null_unspecified dateApproved;
@property (nonatomic, strong) NSDate * _Null_unspecified dateCreated;
@property (nonatomic, strong) NSDate * _Null_unspecified dateLastUpdated;
@property (nonatomic, copy) NSString * _Null_unspecified _description;
@property (nonatomic, copy) NSString * _Null_unspecified externalReference;
@property (nonatomic, copy) NSArray<FeesDetail *> * _Null_unspecified feesDetails;
@property (nonatomic) NSInteger _id;
@property (nonatomic) NSInteger installments;
@property (nonatomic, strong) NSObject * _Null_unspecified metadata;
@property (nonatomic, strong) NSDate * _Null_unspecified moneyReleaseDate;
@property (nonatomic, copy) NSString * _Null_unspecified notificationUrl;
@property (nonatomic, strong) Order * _Null_unspecified order;
@property (nonatomic, copy) NSString * _Null_unspecified paymentMethodId;
@property (nonatomic, copy) NSString * _Null_unspecified paymentTypeId;
@property (nonatomic, copy) NSArray<Refund *> * _Null_unspecified refunds;
@property (nonatomic, copy) NSString * _Null_unspecified statementDescriptor;
@property (nonatomic, copy) NSString * _Null_unspecified status;
@property (nonatomic, copy) NSString * _Null_unspecified statusDetail;
@property (nonatomic) double transactionAmount;
@property (nonatomic) double transactionAmountRefunded;
@property (nonatomic, strong) TransactionDetails * _Null_unspecified transactionDetails;
@property (nonatomic, copy) NSString * _Null_unspecified collectorId;
@property (nonatomic) double couponAmount;
@property (nonatomic, strong) NSNumber * _Nonnull differentialPricingId;
@property (nonatomic) NSInteger issuerId;
+ (Payment * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
+ (NSDate * _Null_unspecified)getDateFromString:(NSString * _Null_unspecified)string;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK24PaymentDateTableViewCell")
@interface PaymentDateTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK22PaymentIDTableViewCell")
@interface PaymentIDTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK13PaymentMethod")
@interface PaymentMethod : Serializable
@property (nonatomic, copy) NSString * _Null_unspecified _id;
@property (nonatomic, copy) NSString * _Null_unspecified name;
@property (nonatomic, copy) NSString * _Null_unspecified paymentTypeId;
@property (nonatomic, copy) NSArray<Setting *> * _Null_unspecified settings;
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified additionalInfoNeeded;
- (BOOL)isIssuerRequired;
- (BOOL)isSecurityCodeRequired:(NSString * _Nonnull)bin;
- (BOOL)isAdditionalInfoNeeded:(NSString * _Null_unspecified)param;
+ (PaymentMethod * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK16PaymentMethodRow")
@interface PaymentMethodRow : NSObject
@property (nonatomic, copy) NSString * _Nullable label;
@property (nonatomic, strong) Card * _Nullable card;
@property (nonatomic, copy) NSString * _Nullable icon;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK26PaymentMethodTableViewCell")
@interface PaymentMethodTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setLabel:(NSString * _Nonnull)label;
- (void)setImageWithName:(NSString * _Nonnull)imageName;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK28PaymentMethodsViewController")
@interface PaymentMethodsViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14PaymentService")
@interface PaymentService : MercadoPagoService
- (void)getPaymentMethods:(NSString * _Nonnull)method uri:(NSString * _Nonnull)uri public_key:(NSString * _Nonnull)public_key success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)getInstallments:(NSString * _Nonnull)method uri:(NSString * _Nonnull)uri public_key:(NSString * _Nonnull)public_key bin:(NSString * _Nonnull)bin amount:(double)amount issuer_id:(NSNumber * _Nullable)issuer_id payment_type_id:(NSString * _Nonnull)payment_type_id success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)getIssuers:(NSString * _Nonnull)method uri:(NSString * _Nonnull)uri public_key:(NSString * _Nonnull)public_key payment_method_id:(NSString * _Nonnull)payment_method_id success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK25PaymentTotalTableViewCell")
@interface PaymentTotalTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Phone")
@interface Phone : NSObject
@property (nonatomic, copy) NSString * _Nullable areaCode;
@property (nonatomic, copy) NSString * _Nullable number;
+ (Phone * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK23PromoEmptyTableViewCell")
@interface PromoEmptyTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImageView;
@class UILabel;

SWIFT_CLASS("_TtC14MercadoPagoSDK18PromoTableViewCell")
@interface PromoTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified issuerImageView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified sharesSubtitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified paymentMethodsSubtitle;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27PromoTyCDetailTableViewCell")
@interface PromoTyCDetailTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (void)setLabelWithIssuerName:(NSString * _Nonnull)issuer legals:(NSString * _Nonnull)legals;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK19PromoViewController")
@interface PromoViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPublicKey:(NSString * _Nonnull)publicKey OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK13PromosService")
@interface PromosService : MercadoPagoService
- (void)getPromos:(NSString * _Nonnull)url method:(NSString * _Nonnull)method public_key:(NSString * _Nonnull)public_key success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK22PromosTyCTableViewCell")
@interface PromosTyCTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK23PromosTyCViewController")
@interface PromosTyCViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK6Refund")
@interface Refund : NSObject
@property (nonatomic) double amount;
@property (nonatomic, strong) NSDate * _Null_unspecified dateCreated;
@property (nonatomic) NSInteger _id;
@property (nonatomic, strong) NSObject * _Null_unspecified metadata;
@property (nonatomic) NSInteger paymentId;
@property (nonatomic, copy) NSString * _Null_unspecified source;
@property (nonatomic, copy) NSString * _Null_unspecified uniqueSequenceNumber;
+ (Refund * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14SavedCardToken")
@interface SavedCardToken : NSObject
@property (nonatomic, copy) NSString * _Nullable cardId;
@property (nonatomic, copy) NSString * _Nullable securityCode;
@property (nonatomic, strong) Device * _Nullable device;
@property (nonatomic) BOOL securityCodeRequired;
- (nonnull instancetype)initWithCardId:(NSString * _Nonnull)cardId securityCode:(NSString * _Nonnull)securityCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCardId:(NSString * _Nonnull)cardId securityCode:(NSString * _Nullable)securityCode securityCodeRequired:(BOOL)securityCodeRequired OBJC_DESIGNATED_INITIALIZER;
- (BOOL)validate;
- (BOOL)validateCardId;
- (BOOL)validateSecurityCode;
- (NSString * _Nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK12SecurityCode")
@interface SecurityCode : Serializable
@property (nonatomic) NSInteger length;
@property (nonatomic, copy) NSString * _Null_unspecified cardLocation;
@property (nonatomic, copy) NSString * _Null_unspecified mode;
+ (SecurityCode * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@interface Serializable (SWIFT_EXTENSION(MercadoPagoSDK))
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK7Setting")
@interface Setting : Serializable
@property (nonatomic, strong) Bin * _Null_unspecified bin;
@property (nonatomic, strong) CardNumber * _Null_unspecified cardNumber;
@property (nonatomic, strong) SecurityCode * _Null_unspecified securityCode;
+ (Setting * _Nullable)getSettingByBin:(NSArray<Setting *> * _Null_unspecified)settings bin:(NSString * _Null_unspecified)bin;
+ (Setting * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Token")
@interface Token : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified _id;
@property (nonatomic, copy) NSString * _Null_unspecified publicKey;
@property (nonatomic, copy) NSString * _Null_unspecified cardId;
@property (nonatomic, copy) NSString * _Null_unspecified luhnValidation;
@property (nonatomic, copy) NSString * _Null_unspecified status;
@property (nonatomic, copy) NSString * _Null_unspecified usedDate;
@property (nonatomic) NSInteger cardNumberLength;
@property (nonatomic, strong) NSDate * _Null_unspecified creationDate;
@property (nonatomic, copy) NSString * _Null_unspecified truncCardNumber;
@property (nonatomic) NSInteger securityCodeLength;
@property (nonatomic) NSInteger expirationMonth;
@property (nonatomic) NSInteger expirationYear;
@property (nonatomic, strong) NSDate * _Null_unspecified lastModifiedDate;
@property (nonatomic, strong) NSDate * _Null_unspecified dueDate;
- (nonnull instancetype)initWith_id:(NSString * _Nonnull)_id publicKey:(NSString * _Nonnull)publicKey cardId:(NSString * _Null_unspecified)cardId luhnValidation:(NSString * _Null_unspecified)luhnValidation status:(NSString * _Null_unspecified)status usedDate:(NSString * _Null_unspecified)usedDate cardNumberLength:(NSInteger)cardNumberLength creationDate:(NSDate * _Null_unspecified)creationDate truncCardNumber:(NSString * _Null_unspecified)truncCardNumber securityCodeLength:(NSInteger)securityCodeLength expirationMonth:(NSInteger)expirationMonth expirationYear:(NSInteger)expirationYear lastModifiedDate:(NSDate * _Null_unspecified)lastModifiedDate dueDate:(NSDate * _Nullable)dueDate OBJC_DESIGNATED_INITIALIZER;
+ (Token * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18TransactionDetails")
@interface TransactionDetails : NSObject
@property (nonatomic) double couponAmount;
@property (nonatomic, copy) NSString * _Null_unspecified externalResourceUrl;
@property (nonatomic, copy) NSString * _Null_unspecified financialInstitution;
@property (nonatomic) double installmentAmount;
@property (nonatomic) double netReceivedAmount;
@property (nonatomic) double overpaidAmount;
@property (nonatomic) double totalPaidAmount;
+ (TransactionDetails * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIColor (SWIFT_EXTENSION(MercadoPagoSDK))
- (UIColor * _Nonnull)UIColorFromRGB:(NSUInteger)rgbValue;
- (UIColor * _Nonnull)errorCellColor;
- (UIColor * _Nonnull)greenOkColor;
- (UIColor * _Nonnull)redFailureColor;
- (UIColor * _Nonnull)errorValidationTextColor;
- (UIColor * _Nonnull)yellowFailureColor;
- (UIColor * _Nonnull)blueMercadoPago;
- (UIColor * _Nonnull)grayBaseText;
- (UIColor * _Nonnull)grayDark;
- (UIColor * _Nonnull)grayLight;
- (UIColor * _Nonnull)grayLines;
- (UIColor * _Nonnull)backgroundColor;
- (UIColor * _Nonnull)white;
- (UIColor * _Nonnull)installments;
@end


@interface UIDevice (SWIFT_EXTENSION(MercadoPagoSDK))
@end

@class NSString;
@class UIActivityIndicatorView;

SWIFT_CLASS("_TtC14MercadoPagoSDK13UILoadingView")
@interface UILoadingView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)rect text:(NSString * _Nonnull)text OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) UILabel * _Nonnull label;
@property (nonatomic, strong) UIActivityIndicatorView * _Nonnull spinner;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK19VaultViewController")
@interface VaultViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
@property (nonatomic, copy) void (^ _Nullable callback)(PaymentMethod * _Nonnull, NSString * _Nullable, NSNumber * _Nullable, NSInteger);
@property (nonatomic, strong) UILoadingView * _Null_unspecified loadingView;
@property (nonatomic, strong) Card * _Nullable selectedCard;
@property (nonatomic, strong) PayerCost * _Nullable selectedPayerCost;
@property (nonatomic, strong) CardToken * _Nullable selectedCardToken;
@property (nonatomic, strong) PaymentMethod * _Nullable selectedPaymentMethod;
@property (nonatomic, strong) Issuer * _Nullable selectedIssuer;
@property (nonatomic, copy) NSArray<Card *> * _Nullable cards;
@property (nonatomic, copy) NSArray<PayerCost *> * _Nullable payerCosts;
@property (nonatomic) BOOL securityCodeRequired;
@property (nonatomic) NSInteger securityCodeLength;
@property (nonatomic, copy) NSString * _Nullable bin;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable supportedPaymentTypes;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)scrollToRow:(NSIndexPath * _Nonnull)indexPath;
- (void)declareAndInitCells;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)showViewController:(UIViewController * _Nonnull)vc;
- (void)loadPayerCosts;
- (void)submitForm;
@end

#pragma clang diagnostic pop
